# Generated by Django 5.2 on 2025-06-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="anime_images/"),
                ),
                ("trailer_url", models.URLField(blank=True, null=True)),
                ("studio", models.CharField(blank=True, max_length=100, null=True)),
                ("episodes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("upcoming", "Upcoming"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ongoing",
                        max_length=50,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("tv", "TV"),
                            ("movie", "Movie"),
                            ("ova", "OVA"),
                            ("ona", "ONA"),
                            ("special", "Special"),
                            ("tv_short", "TV Short"),
                        ],
                        default="tv",
                        max_length=50,
                    ),
                ),
                (
                    "classification_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
